# pipeline to build simple plugin in go
workspace:
  base: /go

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go get
      - go build -o weather-plugin

  publish:
    docker:
      username: $$DOCKER_USER
      password: $$DOCKER_PASSWORD
      repo: heflik/weather-plugin
      tag: latest
      file: Dockerfile
