# pipeline to build simple plugin in go
workspace:
  base: /go

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go get
      - go build -o weather-plugin
      - env
      - echo $${DOCKER_USER} heflik_test

  publish:
    image: plugins/docker
    environments:
      - USER="$${DOCKER_USER}"
      - PASS="$${DOCKER_PASSWORD}"
    username: $USER
    password: $PASS
    repo: $USER/weather-plugin
    tag: latest
    file: Dockerfile
