# pipeline to build simple plugin in go
workspace:
  base: /go

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go get
      - go build -o weather-plugin
      - echo $$DOCKER_USER

  publish:
    image: plugins/docker
    username: ${docker_username}
    password: ${docker_password}
    repo: ${docker_username}/weather-plugin
    tag: latest
    file: Dockerfile
