# pipeline to build simple plugin in go
workspace:
  base: /go

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go get
      - go build -o weather-plugin
  publish:
    docker:
      username: $$DOCKER_USER
      password: $$DOCKER_PASSWORD
      repo: heflik/weather-plugin
      tag: latest
  plugin:
    name: Drone weather plugin
    desc: Push weather data into your build log
    type: notify
    image: heflik/weather-plugin
    labels:
      - test1