# pipeline to build simple plugin in go
workspace:
  base: /go

pipeline:
  build:
    image: golang
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go get
      - go build -o weather-plugin

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    registry: docker.io
    repo: heflik/weather-plugin
    tag: latest
    file: Dockerfile
